IF EXISTS (SELECT * 
			FROM sys.objects 
			WHERE object_id = OBJECT_ID(N'[ADMINISTRATOR]') 
				AND type in (N'U'))
BEGIN
	DROP TABLE [ADMINISTRATOR]
END
GO

IF EXISTS (SELECT * 
			FROM sys.objects 
			WHERE object_id = OBJECT_ID(N'[CLIENT]') 
				AND type in (N'U'))
BEGIN
	DROP TABLE [CLIENT]
END
GO

IF EXISTS (SELECT * 
			FROM sys.objects 
			WHERE object_id = OBJECT_ID(N'[CLIENT_TYPES]') 
				AND type in (N'U'))
BEGIN
	DROP TABLE [CLIENT_TYPES]
END
GO

IF EXISTS (SELECT * 
			FROM sys.objects 
			WHERE object_id = OBJECT_ID(N'[TRAVEL]') 
				AND type in (N'U'))
BEGIN
	DROP TABLE [TRAVEL]
END
GO


CREATE TABLE ADMINISTRATOR 
( 
	ID				INT NOT NULL IDENTITY(1, 1), 
	UPDATE_COUNTER  INT NOT NULL,
	FIRST_NAME		NVARCHAR(64) NOT NULL,
	LAST_NAME		NVARCHAR(64) NOT NULL,
	UCN				NVARCHAR(16) NOT NULL,
	ID_CLIENT		INT NOT NULL, 

CONSTRAINT PK_ADMINISTRATOR_ID PRIMARY KEY (ID)
)
GO

CREATE TABLE CLIENT 
( 
	ID				INT NOT NULL IDENTITY(1, 1), 
	UPDATE_COUNTER  INT NOT NULL,
	[NAME]			NVARCHAR NOT NULL,
	SALARY			FLOAT NOT NULL,
	ID_TYPE_CLIENT	INT NOT NULL,

CONSTRAINT PK_CLIENT_ID PRIMARY KEY (ID)
)
GO

CREATE TABLE CLIENT_TYPES 
( 
	ID				INT NOT NULL IDENTITY(1, 1), 
	UPDATE_COUNTER  INT NOT NULL,
	CLIENT_TYPE		NVARCHAR NOT NULL,

CONSTRAINT PK_CLIENT_TYPES_ID PRIMARY KEY (ID)
)
GO

CREATE TABLE TRAVEL 
( 
	ID				  INT NOT NULL IDENTITY(1, 1), 
	UPDATE_COUNTER    INT NOT NULL,
	TRAVEL_TYPE		  NVARCHAR NOT NULL,
	ID_DESTIONATION   INT NOT NULL, 
	ID_TRANSPORT_TYPE INT NOT NULL,

CONSTRAINT PK_TRAVEL_ID PRIMARY KEY (ID)
)
GO
